Sync mirror
djmaxus/matlab-repo-init pull request #24
Opened 2024-11-27 16:29 UTC by alexdewar

This PR adds a CI workflow to push any changes made to this repo to the [fork on the ICL org](https://github.com/ImperialCollegeLondon/matlab-repo-init).

The problem with doing this is that by default the GitHub runner won't have the requisite permissions to push to a repository other than this one. I've got round this by using the [webfactory/ssh-agent](https://github.com/marketplace/actions/webfactory-ssh-agent) GitHub Action, but it does require manual setup (see the website for details).

In brief, you'll need to:

1. Generate a new ssh key locally
2. Add this key to your GitHub account so it's authorised to access both of the repos
3. Add a new repository secret called `SSH_PRIVATE_KEY` containing the contents of the private counterpart to the key you've just added to GitHub

(There are more details on the linked page.)

Let's hold off on merging this until everything's set up properly, just so we know it'll definitely work. If you're unsure about anything, please ask!

Closes #9.

2024-11-27 16:56 UTC, djmaxus commented on .github/workflows/sync-mirror.yml
Is it correct that this action syncs only the default branch?
If so, that would be a behaviour I'd prefer. 
On top of that, I would also push tags because they represent discrete versions.
Do you think we could add this functionality?

2024-11-27 16:58 UTC, djmaxus commented on .github/workflows/sync-mirror.yml
> +          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
I would set a more specific name for the secret as long as it has a limited purpose, i.e., keeping the fork for `matlab-repo-init` in sync.

```suggestion
          ssh-private-key: ${{ secrets.MATLAB_TEMPLATE_MIRROR_SSH_PRIVATE_KEY }}
```

2024-11-27 16:59 UTC, djmaxus requested changes
Thanks a lot! I have left only a few tiny suggestions to discuss

2024-11-28 12:26 UTC, djmaxus commented
@alexdewar I've configured the SSH key

2024-11-28 12:34 UTC, alexdewar commented
Great.

I think I've addressed your changes now, so if you're happy, I think we can merge.

2024-11-28 12:37 UTC, djmaxus approved these changes

2024-11-28 12:40 UTC, djmaxus commented
Awesome! I'm going to test the last step of the sequence of git commands from the last workflow step manually on my machine, then I'm happy to merge!

2024-11-28 14:15 UTC, merged