Define Markdownlint GitHub Action and set
djmaxus/matlab-repo-init pull request #25
Opened 2024-11-27 16:37 UTC by HarmonicReflux

This Pull request adds a Markdownlinter to GitHub Actions to make sure `*.md ` files are formatted to standard. 

In particular, the following features were cofigured:
- Added `name` fields to the workflow and job for better identification in GitHub Actions UI
- Set workflow triggers to `main` and `develop` branches for both push and pull request events
- Enhanced step descriptions for clarity and easier debugging
- Ensured markdownlint CLI2 automatically fixes issues and targets all Markdown files

Closes #22.

2024-11-27 17:01 UTC, djmaxus requested changes

2024-11-27 17:01 UTC, djmaxus commented on .github/workflows/markdownlint-cli2-action.yml
> +          globs: '**/*.md'
Is it possible to not check the spelling in the auto-generated `CHANGELOG.md`?

2024-11-28 14:40 UTC, djmaxus approved these changes
Looks and works great! I'm happy to merge this now. Thank you @HarmonicReflux

2024-11-28 14:43 UTC, merged

2024-11-28 15:15 UTC, alexdewar commented
For future reference, I'd be wary about merging someone's PR if they've marked it as draft! That can often mean something isn't finished or it hasn't been tested properly. Not sure if this is the case or not here.

2024-11-29 11:06 UTC, djmaxus commented
@alexdewar yes, absolutely! This is a fair point, and I am so sorry for my hurry.
I was confused about whether I accidentally marked it as a draft and didn't double-check.

My apologies, @HarmonicReflux 🙏🏼